import '@fortawesome/fontawesome-free/js/fontawesome.js'
import '@fortawesome/fontawesome-free/js/solid.js'
import './style.scss'
import './site/index.js'
import './pwa/index.js'
import './nav/index.js'
import './page/index.js'
import './turtle/index.js'
